{{- range $path, $_ := .Files.Glob "sa-link/**.yaml" }}
{{- $v := $.Files.Get $path | fromYaml }}
{{- if $v.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    argocd.argoproj.io/sync-wave: "1"
  name: {{$v.name}}-sealedsecret
  namespace: confluent
spec:
  encryptedData:
    password: {{$v.password}}
---
{{- end }}
{{- end }}