{{- range $path, $_ := .Files.Glob "sa-link/**.yaml" }}
{{- $v := $.Files.Get $path | fromYaml }}
{{- if $v.enabled }}
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  labels:
    app.kubernetes.io/name: mep-service-accounts
  name: sa-schema-resourceowner-{{$v.name}}
  namespace: confluent
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  clustersScopeByIds: 
    schemaRegistryClusterId: id_schemaregistry_confluent
  kafkaRestClassRef:
    name: default
  principal:
    name: {{$v.name}}
    type: user
  resourcePatterns:
  - name: {{$v.name}}.
    patternType: PREFIXED
    resourceType: Subject
  role: ResourceOwner
---
{{- end }}
{{- end }}