apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: ldap
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 389
    name: ldap
  - port: 636
    name: ldaps
  clusterIP: None
  selector:
    app: ldap
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: ldap
  ports:
    - port: 389
      targetPort: 389
      nodePort: 30389
