apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: {{print "confluentinc/cp-enterprise-control-center:" .Values.cpServer.version}}
    init: {{print "confluentinc/confluent-init-container:" .Values.confluentInitContainer.version}}
  dataVolumeCapacity: 10Gi
  authorization:
    kafkaRestClassRef:
      name: default
      namespace: confluent
    type: rbac
  externalAccess:
    type: nodePort
    nodePort:
      host: confluent.svc.cluster.local
      nodePortOffset: 30021
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
      tls:
        enabled: false
    mds:
      endpoint: http://kafka.confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: mds-client
      tls:
        enabled: false
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
      tls:
        enabled: false