{{ if .Values.confluentForKubernetes.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-for-kubernetes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: "confluent-for-kubernetes"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: confluent
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./charts/confluent/confluent-for-kubernetes
    repoURL: https://github.com/mamonteiro-kafkaops/confluent-selfservice.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ./values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{ end }}      