apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: kafkauser-schemaregistry-systemadmin
  namespace: confluent
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_confluent
  principal:
    name: kafka
    type: user
  role: SystemAdmin